### ISSUE TITLE
Hardcoded hostname in lambda.js

### ISSUE THREAD

**Issue by ger-cloud** [safesoftware/codeless-api-demo#1]
### Description:
In the file `/api_gateway/lambda.js`, a hostname is hardcoded in line number 16.

The key `hostname` should be mapped to the variable `host` defined in line number 4.

@stewgeo I have a fix ready for a pull request on my local branch, but I don't have permission to create a new branch for this repo. Feel free to add me and I'll make the change.

**Comment by stewgeo** [comment]
Thanks. I added you as an admin.
